# Generated by Django 4.1.7 on 2023-04-09 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Product', 'published_date', 'pub_date'),
    ]
